# Site settings
title: codemunkies
email: steve@codemunki.es
description: ""
baseurl: ""
url: "http://www.codemunki.es"
github-username: steve-codemunkies
twitter-username: codemunkies
twitter-personal-username: SteveHocking
stackoverflow-username: steve
stackoverflow-userid: 747649

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

include: ["keybase.txt", "public.key"]
exclude: [".devcontainer", ".vscode"]